name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  linux-unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@sm/node-20
  windows-unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@sm/node-20
